- name: Change file ownership(root) and permissions(-rw-r--r--) for hosts.allow
  ansible.builtin.file:
                  path: /etc/hosts.allow
                  owner: root
                  group: root
                  mode: '0644'
  when:
      - rhel8_rule_13
  tags:
      - hosts                

- name: Change file ownership(root) and permissions(-rw-r--r--) for hosts.deny
  ansible.builtin.file:
                  path: /etc/hosts.deny
                  owner: root
                  group: root
                  mode: '0644'
  when:
      - rhel8_rule_14
  tags:
      - hosts
